### ISSUE TITLE
<sw-update-toast> causes an error when SW is install for the first time

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [morbidick/serviceworker-helpers#3]
I've added `<sw-update-toast>` to my web app. When I opens the app in the browser for the first time, I get the following error in the browser console:

```
sw-update-toast.html:63 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined
    at navigator.serviceWorker.getRegistration.then (sw-update-toast.html:63)
    at <anonymous>
```

**Comment by FluorescentHallucinogen** [comment]
@morbidick @jakearchibald PTAL.

**Comment by FluorescentHallucinogen** [comment]
The problem is `navigator.serviceWorker.getRegistration` resolves to `undefined`, if I opens the app in the browser for the first time. If I reload the page or re-open the app, all is ok, `navigator.serviceWorker.getRegistration` resolves to `ServiceWorkerRegistration`.

**Comment by morbidick** [comment]
Good catch, i just replicated it with a private tab in chrome. I would have expected that the promise doesn't resolve as long as there is no service worker registered. So its probably best to wrap it in another if statement.

**Comment by morbidick** [comment]
the behaviour is in the docs... https://developer.mozilla.org/de/docs/Web/API/ServiceWorkerContainer/getRegistration

**Comment by FluorescentHallucinogen** [comment]
Tested in the latest Chrome Stable and Chrome Canary.

**Comment by morbidick** [comment]
just tested it locally, with the wrapping condition it doesnt throw any errors and should register as soon as the app is opened the second time (as far as i understand thats the expected behaviour). Would be nice to find a way to reproducible test it (like stated in #2).

**Comment by FluorescentHallucinogen** [comment]
> with the wrapping condition it doesnt throw any errors and should register as soon as the app is opened the second time (as far as i understand thats the expected behaviour)

No, this is not an expected behaviour, the event listener should be registered as soon as the app is opened for the first time, not the second time.

It is a good practice to show "App is ready for offline use" toast when the app has loaded for the first time. You can see it in action on e.g. https://www.chromestatus.com and https://www.polymer-project.org.

**Comment by FluorescentHallucinogen** [comment]
See https://github.com/GoogleChrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js

**Comment by FluorescentHallucinogen** [comment]
The problem is you call `navigator.serviceWorker.getRegistration` in the `<sw-update-toast>`'s `ready()` lifecycle callback. In this moment (if the app has loaded for the first time) the list of active `ServiceWorkerRegistration` objects is empty and `navigator.serviceWorker.getRegistration` promise resolves to `undefined`.

The wrapping condition that you added does not really solve the problem, it just hide symptoms that something is wrong (errors in the browser console). The condition checks if `registration !== undefined`. If `registration == undefined`, nothing will happen, the listener for `updatefound` event will not be registered, and the web component will not do the work for which it was designed.

Let's say the user never reloaded the app or any pages of the app since it was opened for the first time. In this case the toast requesting the user to reload the page when a new content is available will never be shown.

**Comment by FluorescentHallucinogen** [comment]
@jakearchibald Could you please help?

**Comment by FluorescentHallucinogen** [comment]
@gauntface @jeffposnick PTAL.

**Comment by jeffposnick** [comment]
Not super-familiar with the specifics of this Polymer element, but if you're looking for a promise that you could wait on that will eventually be resolved with a `ServiceWorkerRegistration`, then `navigator.serviceWorker.ready` would probably fit the bill: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/ready

**Comment by FluorescentHallucinogen** [comment]
@jeffposnick Thanks! But `navigator.serviceWorker.ready.then` doesn't fit the bill, because if `navigator.serviceWorker.ready.then` is used, it's not possible to show the toast when the app has loaded for the first time:

```js
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.ready.then((registration) => {
    registration.addEventListener('updatefound', () => {
      var installingSW = registration.installing;
      installingSW.addEventListener('statechange', () => {
        switch (installingSW.state) {
          case 'installed':
            if (navigator.serviceWorker.controller) {
              console.log('A new service worker has been installed, replacing the current service worker. Please reload the page.');
            } else {
              // This will never execute
              console.log('A service worker has been installed for the first time.');
            }
            break;
          case 'redundant':
            console.log('A new service worker is replacing the current service worker, or the current service worker is being discarded due to an install failure.');
            break;
        }
      })
    })
  })
}
```

Seems, using `navigator.serviceWorker.getRegistration` inside the listener of `load` event is the suitable solution. See #4.
